name: Lint Codebase

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write
  packages: read
  statuses: write

jobs:
  super-lint:
    name: Lint and Autofix
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super Linter
        uses: super-linter/super-linter/slim@v7.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CHECKOV: false
          VALIDATE_PYTHON_PYLINT: false
          FIX_SHELL_SHFMT: true
          FIX_YAML_PRETTIER: true
          FIX_JSON: true
          FIX_JSON_PRETTIER: true
          FIX_MARKDOWN: true
          FIX_PYTHON_BLACK: true
          FIX_PYTHON_ISORT: true
          # Add more FIX_ variables as needed

      - name: Check for linting changes
        id: changed
        run: |
          git diff --quiet || echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Create New Pull Request If Needed
        if: steps.changed.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Github bot : fix linting issues"
          commit_options: "--no-verify --signoff"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
